api:
  baseUri: ""
  console:
    state: "stopped"
http:
  listener:
    port: "8092"
  request:
    method:
      restriction:
        createupdate: "PUT"
        delete: "DELETE"
      blocking:
        createupdate: "PUT"
        delete: "DELETE"
  response:
    code:
      success: "200"
  constants:
    response:
      success: "SUCCESS"
      failure: "ERROR"

application:
  name: "ent-orders-salesforce-sapi"   
ordercreation:
  url: "https://henryschein-na--pldevteam3.sandbox.my.salesforce.com/services/apexrest/SFOrderCreation"
  token: "https://henryschein-na--pldevteam3.sandbox.my.salesforce.com/services/oauth2/token"
# salesforce SAPI configurations
country:
  us: "US"  
  canada: "CANADA"

  
operations:
  constants:
    errorType:
      badRequest: "APIKIT:BAD_REQUEST"
      notFound: "APIKIT:NOT_FOUND"
      methodNotAllowed: "APIKIT:METHOD_NOT_ALLOWED"
      notAcceptable: "APIKIT:NOT_ACCEPTABLE"
      unsupportedMediaType: "APIKIT:UNSUPPORTED_MEDIA_TYPE"
      notImplemented: "APIKIT:NOT_IMPLEMENTED"
      gatewayTimeout: "HTTP:GATEWAY_TIMEOUT"

    errorCode:
      badRequest: "400"
      notFound: "404"
      methodNotAllowed: "405"
      notAcceptable: "500"
      unsupportedMediaType: "415"
      notImplemented: "501"
      internalServerError: "500"
  
    cron:
      us: "* 0/1 * * * ? *"
      can: "* 0/1 * * * ? *"
    source: "E&T"
    target: "Siebel"
    country:
      us: "US"
      canada: "Canada"