api:
  baseUri: ""
  console:
    state: "stopped"
http:
  listener:
    port: "8092"
  request:
    basepath: "/services"
  response:
    code:
      success: "200"
  constants:
    response: 
      success: "SUCCESS"
      failure: "ERROR"

application:
  name: "ent-orders-salesforce-sapi"   
ordercreation:
  url: "https://henryschein-na--pldevteam3.sandbox.my.salesforce.com/services/apexrest/SFOrderCreation"
  token: "https://henryschein-na--pldevteam3.sandbox.my.salesforce.com/services/oauth2/token"
# salesforce SAPI configurations
country:
  us: "US"  
  canada: "CANADA"


salesforce:
  grant:
    type: "password"
  headers:
    client:
      username: "equipmentorders.integrationuser@ibm.com.pldevteam3"
      password: "Amlzsk@123zyShVIvE316wiu1EAlpG8Ac0f"
      id: "3MVG973QtA4.tpvmU7itl2xfAfZrm1kGUj2HMwuRVusoPKm4UoWrR2hqrtlUsicLlv.UHKpjPxsb8gw3IU_qu"
      secret: "F697E1F5B2F0CA2A2375A3BBDE18C94F7C208732A35AEABCFB8D8CCE6108CF60"  
operations:
  constants:
    errorType:
      badRequest: "APIKIT:BAD_REQUEST"
      notFound: "APIKIT:NOT_FOUND"
      methodNotAllowed: "APIKIT:METHOD_NOT_ALLOWED"
      notAcceptable: "APIKIT:NOT_ACCEPTABLE"
      unsupportedMediaType: "APIKIT:UNSUPPORTED_MEDIA_TYPE"
      notImplemented: "APIKIT:NOT_IMPLEMENTED"
      gatewayTimeout: "HTTP:GATEWAY_TIMEOUT"

    errorCode:
      badRequest: "400"
      notFound: "404"
      methodNotAllowed: "405"
      notAcceptable: "500"
      unsupportedMediaType: "415"
      notImplemented: "501"
      internalServerError: "500"
    source: "E&T"
    target: "Siebel"
    country:
      us: "US"
      canada: "Canada"
endpoint:
  order:
    creation: "/apexrest/SFOrderCreation"
    token: "/oauth2/token"